#!/usr/bin/env python3
"""Layer 1 - PHPUnit (unit / functional).

Behaviour:
  * If the extension already ships a PHPUnit config + tests, run them (when a
    phpunit binary is reachable) and parse the JUnit result.
  * If it has no tests, scaffold a minimal, runnable suite into the report
    directory using the CURRENT conventions (not the archived joomla/test-unit
    package) so the developer has a real starting point.

The scaffolds are written into <out-dir>/phpunit-scaffold/ by default and are
never copied into the source tree unless `--write-scaffold` is passed (and even
then existing files are never overwritten).

Standalone:
    python3 layer_phpunit.py <source-tree> [--json] [--run] [--write-scaffold]
"""

import argparse
import os
import sys
import tempfile
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import cms_common as cc          # noqa: E402
import detect_target as dt       # noqa: E402

LAYER = "phpunit"


# --- scaffold templates (verified against Joomla 4/5 + WP-CLI conventions) --

JOOMLA_PHPUNIT_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Minimal PHPUnit config for a Joomla 4/5 extension (PHPUnit ^9.6, PHP 8.1+).
     Joomla pins phpunit/phpunit:^9.6 - do NOT author PHPUnit 10-only syntax.
     The archived joomla/test-unit Packagist package is NOT used. -->
<phpunit bootstrap="tests/Unit/bootstrap.php" colors="true" failOnWarning="true">
  <testsuites>
    <testsuite name="Unit">
      <directory suffix="Test.php">./tests/Unit</directory>
    </testsuite>
  </testsuites>
</phpunit>
"""

JOOMLA_BOOTSTRAP = """<?php
/**
 * Minimal unit-test bootstrap for a Joomla extension.
 * Extensions reference _JEXEC and JPATH_* globals that only exist inside a
 * running CMS, so we define safe defaults here. For integration tests against
 * a real DB, use the full joomla-cms tests/Unit/bootstrap.php instead.
 */
\\error_reporting(E_ALL);
if (!\\defined('_JEXEC'))           \\define('_JEXEC', 1);
if (!\\defined('JPATH_BASE'))       \\define('JPATH_BASE', \\getcwd());
if (!\\defined('JPATH_ROOT'))       \\define('JPATH_ROOT', JPATH_BASE);
if (!\\defined('JPATH_SITE'))       \\define('JPATH_SITE', JPATH_BASE);
if (!\\defined('JPATH_ADMINISTRATOR')) \\define('JPATH_ADMINISTRATOR', JPATH_BASE . '/administrator');
if (!\\defined('JPATH_LIBRARIES'))  \\define('JPATH_LIBRARIES', JPATH_BASE . '/libraries');

$autoload = JPATH_BASE . '/vendor/autoload.php';
if (\\is_file($autoload)) {
    require $autoload;
}
"""

JOOMLA_SAMPLE_TEST = """<?php
namespace Tests\\Unit;

use PHPUnit\\Framework\\TestCase;

/**
 * Smoke test that does not need a running CMS. Replace with tests that extend
 * Joomla\\Tests\\Unit\\UnitTestCase once you wire the full Joomla unit harness
 * (see references/phpunit.md).
 */
final class ManifestSanityTest extends TestCase
{
    public function testManifestExists(): void
    {
        $candidates = \\glob(\\getcwd() . '/*.xml') ?: [];
        $this->assertNotEmpty($candidates, 'Expected an installation manifest at the extension root.');
    }

    public function testArithmeticHarness(): void
    {
        // Proves the harness itself runs; delete once you add real tests.
        $this->assertSame(3, 1 + 2);
    }
}
"""

WP_PHPUNIT_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Minimal PHPUnit config for a WordPress plugin (PHPUnit ^9.6, PHP 8.x).
     Generated by `wp scaffold plugin-tests` in real projects. -->
<phpunit bootstrap="tests/bootstrap.php" backupGlobals="false" colors="true">
  <testsuites>
    <testsuite name="default">
      <directory prefix="test-" suffix=".php">./tests/</directory>
      <exclude>./tests/test-sample.php</exclude>
    </testsuite>
  </testsuites>
</phpunit>
"""

WP_BOOTSTRAP = """<?php
/**
 * WordPress plugin test bootstrap (mirrors `wp scaffold plugin-tests`).
 * Requires the WP test library: run bin/install-wp-tests.sh first, or set
 * WP_TESTS_DIR. yoast/phpunit-polyfills is mandatory since WP 5.8.2.
 */
$_tests_dir = getenv('WP_TESTS_DIR') ?: rtrim(sys_get_temp_dir(), '/\\\\') . '/wordpress-tests-lib';
if (!file_exists("{$_tests_dir}/includes/functions.php")) {
    fwrite(STDERR, "Could not find {$_tests_dir}/includes/functions.php - run bin/install-wp-tests.sh\\n");
    exit(1);
}
require_once "{$_tests_dir}/includes/functions.php";

function _manually_load_plugin() {
    $plugin_file = getenv('CMS_TEST_PLUGIN_FILE') ?: 'PLUGIN_REQUIRE_PATH';
    require $plugin_file;
}
tests_add_filter('muplugins_loaded', '_manually_load_plugin');

require "{$_tests_dir}/includes/bootstrap.php";
"""

WP_ACTIVATION_TEST = """<?php
/**
 * Exercises the activation hook - the WordPress analogue of a Joomla install
 * script. register_activation_hook() callbacks do NOT fire just because the
 * plugin file is loaded; you must call activate_plugin() explicitly.
 */
class Test_Activation extends WP_UnitTestCase {

    public function test_plugin_activates_without_error() {
        activate_plugin('PLUGIN_BASENAME');
        $this->assertTrue(is_plugin_active('PLUGIN_BASENAME'));
    }

    public function test_harness_runs() {
        // Proves the WP test harness booted; delete once you add real tests.
        $this->assertTrue(function_exists('do_action'));
    }
}
"""


def _php_single_quoted(value):
    return str(value).replace("\\", "\\\\").replace("'", "\\'")


def _scaffold(platform, manifest, source_root=None):
    """Return {relpath: contents} for a minimal suite."""
    if platform == dt.JOOMLA:
        return {
            "phpunit.xml.dist": JOOMLA_PHPUNIT_XML,
            "tests/Unit/bootstrap.php": JOOMLA_BOOTSTRAP,
            "tests/Unit/ManifestSanityTest.php": JOOMLA_SAMPLE_TEST,
        }
    main_file = (manifest or {}).get("path", "my-plugin.php")
    main_file = main_file.replace("\\", "/").lstrip("./") or "my-plugin.php"
    require_path = os.path.abspath(os.path.join(source_root, main_file)) if source_root else main_file
    boot = WP_BOOTSTRAP.replace("PLUGIN_REQUIRE_PATH", _php_single_quoted(require_path))
    act = WP_ACTIVATION_TEST.replace("PLUGIN_BASENAME", main_file)
    return {
        "phpunit.xml.dist": WP_PHPUNIT_XML,
        "tests/bootstrap.php": boot,
        "tests/test-activation.php": act,
    }


# --- running an existing suite ---------------------------------------------


def _find_phpunit(source_root):
    for cand in (os.path.join(source_root, "vendor", "bin", "phpunit"),
                 os.path.join(source_root, "vendor", "bin", "phpunit.bat")):
        if os.path.isfile(cand):
            return cand
    return cc.which("phpunit")


def _parse_junit(path):
    try:
        tree = ET.parse(path)
    except (ET.ParseError, OSError):
        return None
    root = tree.getroot()
    # The top-level <testsuites> (or a single <testsuite>) carries the totals.
    # Use an explicit None check: ElementTree elements with no children are
    # falsy, so `find(...) or root` would wrongly fall back to the outer node.
    found = root.find("testsuite")
    node = root if root.tag == "testsuite" else (found if found is not None else root)
    def _int(attr):
        try:
            return int(node.get(attr, "0"))
        except (TypeError, ValueError):
            return 0
    return {
        "tests": _int("tests"),
        "failures": _int("failures"),
        "errors": _int("errors"),
        "skipped": _int("skipped"),
    }


def _run_existing(ctx, source_root, config_rel, checks, artifacts):
    phpunit = _find_phpunit(source_root)
    if not phpunit:
        checks.append(cc.check("phpunit.binary", cc.SKIP,
                               "No phpunit binary found (vendor/bin/phpunit or PATH). "
                               "Run `composer install` in the extension, then re-run with --run."))
        return
    junit_dir = cc.ensure_dir(os.path.join(ctx.get("out_dir", tempfile.gettempdir()), "phpunit"))
    junit = os.path.join(junit_dir, "junit.xml")
    cmd = [phpunit, "-c", config_rel, "--log-junit", junit]
    if ctx["target"]["platform"] == dt.JOOMLA:
        cmd += ["--testsuite", "Unit"]
    res = cc.run_cmd(cmd, cwd=source_root, timeout=ctx.get("timeout", 600))
    counts = _parse_junit(junit) if os.path.isfile(junit) else None
    if os.path.isfile(junit):
        artifacts.append(cc.artifact("junit", junit, "PHPUnit JUnit log"))
    if counts is None:
        status = cc.PASS if res["ok"] else cc.FAIL
        checks.append(cc.check("phpunit.run", status,
                               "phpunit exited {} (no JUnit log parsed).".format(res["returncode"]),
                               evidence=(res["stdout"][-800:] or res["stderr"][-800:])))
        return
    failed = counts["failures"] + counts["errors"]
    status = cc.PASS if (res["ok"] and failed == 0) else cc.FAIL
    checks.append(cc.check("phpunit.run", status,
                           "{tests} tests, {failures} failures, {errors} errors, {skipped} skipped."
                           .format(**counts)))


def _emit_scaffold(ctx, checks, artifacts):
    platform = ctx["target"]["platform"]
    files = _scaffold(platform, ctx["target"].get("manifest"), ctx.get("target_path"))
    out_base = os.path.join(ctx["out_dir"], "phpunit-scaffold")
    written = []
    for rel, content in files.items():
        dest = os.path.join(out_base, rel)
        cc.ensure_dir(os.path.dirname(dest))
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(dest)
        artifacts.append(cc.artifact("scaffold", dest, rel))
    checks.append(cc.check("phpunit.scaffold", cc.PASS,
                           "Generated a minimal {} PHPUnit suite ({} files) under {}. "
                           "See references/phpunit.md to wire the full harness.".format(
                               platform, len(written), out_base)))

    if ctx.get("write_scaffold"):
        root = ctx["target_path"]
        files = _scaffold(platform, ctx["target"].get("manifest"))
        copied, skipped = 0, 0
        for rel in files:
            dest = os.path.join(root, rel)
            if os.path.exists(dest):
                skipped += 1
                continue
            cc.ensure_dir(os.path.dirname(dest))
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(files[rel])
            copied += 1
        checks.append(cc.check("phpunit.scaffold.write", cc.PASS if copied else cc.WARN,
                               "Copied {} new file(s) into the source tree ({} already existed, "
                               "left untouched).".format(copied, skipped)))


# --- entry points -----------------------------------------------------------


def run(ctx):
    started = cc.now_iso()
    desc = ctx["target"]
    if desc["kind"] == "url-live":
        return cc.layer_result(LAYER, [cc.check("applicability", cc.SKIP,
                               "PHPUnit needs the source tree, not a live URL.")],
                               summary="Skipped (live URL).", started_at=started)
    if desc["platform"] == dt.UNKNOWN:
        return cc.layer_result(LAYER, [cc.check("platform", cc.SKIP,
                               "Unknown platform; cannot pick a test harness.")],
                               summary="Skipped (unknown platform).", started_at=started)

    source_root = ctx["target_path"]
    if not os.path.isdir(source_root):
        return cc.layer_result(LAYER, [cc.check("source", cc.SKIP,
                               "PHPUnit needs an unpacked source tree (got a zip or file).")],
                               summary="Skipped (no source tree).", started_at=started)

    checks, artifacts = [], []
    ep = desc.get("entrypoints", {})
    config_rel = ep.get("phpunit_config")

    if config_rel:
        checks.append(cc.check("phpunit.config", cc.PASS, "Found " + config_rel))
        if ctx.get("run"):
            _run_existing(ctx, source_root, config_rel, checks, artifacts)
        else:
            checks.append(cc.check("phpunit.run", cc.SKIP,
                                   "Existing config detected; pass --run to execute it."))
    else:
        checks.append(cc.check("phpunit.config", cc.WARN,
                               "No PHPUnit config found; scaffolding a minimal suite."))
        _emit_scaffold(ctx, checks, artifacts)

    status = cc.rollup_status(checks)
    return cc.layer_result(LAYER, checks, summary="{} phpunit: {}".format(desc["platform"], status),
                           artifacts=artifacts, started_at=started)


def _ctx_from_args(args):
    desc = dt.detect(args.target)
    return {
        "target": desc,
        "target_path": os.path.abspath(args.target),
        "out_dir": args.out_dir,
        "run": args.run,
        "write_scaffold": args.write_scaffold,
        "timeout": args.timeout,
    }


def main(argv=None):
    p = argparse.ArgumentParser(description="PHPUnit layer (run or scaffold).")
    p.add_argument("target", help="source tree of the extension/plugin")
    p.add_argument("--out-dir", default="cms-test-report")
    p.add_argument("--run", action="store_true", help="execute an existing suite if phpunit is available")
    p.add_argument("--write-scaffold", action="store_true", help="also copy the scaffold into the source tree")
    p.add_argument("--timeout", type=int, default=600)
    p.add_argument("--json", action="store_true")
    args = p.parse_args(argv)
    ctx = _ctx_from_args(args)
    cc.ensure_dir(ctx["out_dir"])
    result = run(ctx)
    cc.emit(result, args.json)
    return cc.status_to_exit(result["status"])


if __name__ == "__main__":
    sys.exit(main())
